purecloudlabs/platform-client-sdk-common

- resources/sdk/purecloudjava/extensions/connector/ning/AsyncHttpClientConnector.java
- resources/sdk/purecloudjava/extensions/connector/ning/AsyncHttpClientConnectorProvider.java
- resources/sdk/purecloudjava/extensions/connector/ning/AsyncHttpResponse.java
Adds support for the NIO-based (and actually asynchronous) Ning AsyncHttpClient.
> API-1581 Add Ning AsyncHttpClient connector

- resources/sdk/pureclouddotnet/templates/README.mustache
Update ININ.PureCloudApi to PureCloudPlatform.Client.V2.
> Update README namespace references

- resources/sdk/purecloudjavascript-guest/templates/ApiClient.mustache
- resources/sdk/purecloudjavascript/templates/ApiClient.mustache
removing noisy error logs from http request failures
> NO-JIRA remove http status error console logs

- resources/sdk/purecloudjavascript-guest/config.json
- resources/sdk/purecloudjavascript-guest/extensions/PureCloudRegionHosts.js
- resources/sdk/purecloudjavascript-guest/templates/README.mustache
- resources/sdk/purecloudjavascript-guest/templates/index.mustache
Updated regions for the javaguestsdk.
> Adding regions to javaguestsdk

- resources/sdk/purecloudjava/templates/ApiClient.mustache
- resources/sdk/purecloudjava/templates/README.mustache
- resources/sdk/purecloudjava/templates/pom.mustache
Added the request to ApiClient, updated the pom to include the dependencies. Was able to remove PureCloudRegionHosts from the ApiClient since this is in the same package as APIClient, so it didn't need to be imported. Also included an updated readme.
> Added a helper function for a saml2bearer token request

- resources/sdk/purecloudpython/templates/README.mustache
- resources/sdk/purecloudpython/templates/configuration.mustache
- resources/sdk/purecloudpython/templates/rest.mustache
Can be set up in configuration as `PureCloudPlatformClientV2.configuration.proxy = proxy_url`
> Add proxy support

- resources/sdk/purecloudjava/templates/README.mustache
Changing the example code to function correctly
> README change

- resources/sdk/pureclouddotnet/extensions/Extensions/Notifications/INotificationHandler.cs
- resources/sdk/pureclouddotnet/extensions/Extensions/Notifications/NotificationHandler.cs
Add Interface to INotificationHandler for eaiser dependency injection and unit testing.
> feat(notification): add interface

- resources/sdk/purecloudjava/extensions/connector/ApiClientConnectorProperty.java
- resources/sdk/purecloudjava/templates/ApiClient.mustache
- resources/sdk/purecloudjava/templates/README.mustache
- resources/sdk/purecloudjava/templates/pom.mustache
- resources/sdk/purecloudjava/templates/testng.mustache
- resources/sdk/purecloudjava/tests/ApiClientRetryAsyncTest.java
- resources/sdk/purecloudjava/tests/ApiClientRetryTest.java
API-4076 - Add Retry Logic To Java SDK
> API-4076 - Add Retry Logic To Java SDK

- resources/sdk/purecloudjava/extensions/connector/ApiClientConnectorProperty.java
- resources/sdk/purecloudjava/extensions/connector/apache/ApacheHttpClientConnectorProvider.java
- resources/sdk/purecloudjava/extensions/connector/apache/ApacheHttpCredentialsProvider.java
- resources/sdk/purecloudjava/templates/ApiClient.mustache
- resources/sdk/purecloudjava/templates/README.mustache
Implementing support for authenticated proxies.
Requested here: https://developer.mypurecloud.com/forum/t/using-sdk-with-a-proxy/5496/2
> API-4527 Add authenticated proxy support to Java SDK

- resources/sdk/pureclouddotnet/templates/README.mustache
- resources/sdk/purecloudpython/templates/README.mustache
- resources/sdk/purecloudpython/templates/configuration.mustache
- resources/sdk/purecloudpython/templates/rest.mustache
Requested here: https://developer.mypurecloud.com/forum/t/implementing-proxy-with-authentication/6738
> API-4992 Add authenticated proxy support to python sdk

- resources/sdk/purecloudjava/templates/ApiClient.mustache
- resources/sdk/purecloudjava/templates/README.mustache
I just noticed some variable typo. So put up this PR.
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[TEST] beforeTest
Before test
[SUCCESS] beforeTest
[TEST] traceBasicInformation
PURECLOUD_ENVIRONMENT=mypurecloud.com
PURECLOUD_CLIENT_ID=7de3af06-c0b3-4f9b-af45-72f4a14037cc
userEmail=95f20983-717f-4d30-84f4-c27093c6602c@mypurecloud.com
[SUCCESS] traceBasicInformation
[TEST] authenticate
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[SUCCESS] authenticate
[TEST] createUser
Created user with ID …
```
> API-4076 - Minor typo fixing

- resources/sdk/purecloudjava-guest/templates/pom.mustache
- resources/sdk/purecloudjava/templates/pom.mustache
Github noted some security issues with jackson and asynchttpclient dependencies
> API-4121 Update Java and Java Guest SDK dependencies

- resources/sdk/pureclouddotnet/extensions/Extensions/Notifications/NotificationHandler.cs
- resources/sdk/purecloudjava/extensions/extensions/notifications/NotificationHandler.java
- resources/sdk/purecloudjava/templates/README.mustache
Auto subscribing to "v2.system.socket_closing" and reconnecting to the websocket when a message is received on this topic.
Also adding quiet add for topics without subscribing.
> API-5244: Revamp notification handlers in SDKs

- resources/sdk/pureclouddotnet/extensions/Extensions/AuthExtensions.cs
- resources/sdk/pureclouddotnet/extensions/Extensions/AuthTokenInfo.cs
- resources/sdk/pureclouddotnet/templates/ApiClient.mustache
- resources/sdk/pureclouddotnet/templates/Configuration.mustache
- resources/sdk/pureclouddotnet/templates/README.mustache
- resources/sdk/pureclouddotnet/templates/api_doc.mustache
- resources/sdk/pureclouddotnet/templates/test-ApiClientTests.mustache
- resources/sdk/pureclouddotnet/templates/test-SdkTests.mustache
- resources/sdk/purecloudgo/extensions/usersapi_test.go
- resources/sdk/purecloudgo/templates/README.mustache
- resources/sdk/purecloudgo/templates/api.mustache
- resources/sdk/purecloudgo/templates/apiclient.mustache
- resources/sdk/purecloudgo/templates/configuration.mustache
- resources/sdk/purecloudjava/extensions/extensions/AuthResponse.java
- resources/sdk/purecloudjava/templates/ApiClient.mustache
- resources/sdk/purecloudjava/templates/README.mustache
- resources/sdk/purecloudjavascript/templates/ApiClient.mustache
- resources/sdk/purecloudjavascript/templates/README.mustache
- resources/sdk/purecloudkotlin/extensions/extensions/AuthResponse.kt
- resources/sdk/purecloudkotlin/templates/ApiClient.kt.mustache
- resources/sdk/purecloudkotlin/templates/README.mustache
- resources/sdk/purecloudpython/templates/README.mustache
- resources/sdk/purecloudpython/templates/api_client.mustache
- resources/sdk/purecloudpython/templates/configuration.mustache
Adding token refresh logic to SDKs for Code Authorization flow and adding helper methods for Code Authorization where needed.
> DEVCTR-97 Adding token refresh logic to SDKs for Code Authorization flow

- package-lock.json
- package.json
- resources/sdk/webmessagingjava/config.json
- resources/sdk/webmessagingjava/templates/README.mustache
- resources/sdk/webmessagingjava/templates/WebMessagingClient.mustache
Imlements new Attachment methods for webmessaging
> Devengage 287 webmessaging sdk

- resources/sdk/purecloudgo/templates/go.mod.mustache
- resources/sdk/purecloudgo/templates/go.sum.mustache
- resources/sdk/purecloudgo/templates/model.mustache
Required to facilitate handling for 3 different date formats:
* yyyy-MM-ddTHH:mm:ss.SSS
* yyyy-MM-ddTHH:mm:ss.SSSZ
* yyyy-MM-dd
Related: https://github.com/purecloudlabs/swagger-codegen/pull/39
> Change date and datetime handling in the Go SDK

- resources/sdk/clisdkclient/extensions/experimental_features/experimental_features.go
- resources/sdk/clisdkclient/extensions/models/experimentalfeaturecommands.go
- resources/sdk/clisdkclient/extensions/transform_data/transform_data.go
- resources/sdk/clisdkclient/extensions/utils/render.go
- resources/sdk/clisdkclient/query.yaml
- resources/sdk/clisdkclient/templates/README.mustache
- resources/sdk/clisdkclient/templates/root.mustache
New experimental CLI feature. Transform Data.
> Transform data

- resources/sdk/clisdkclient/extensions/README.md
- resources/sdk/clisdkclient/extensions/transform_data/transform_data.go
moving README to extensions, fixing minor error in Go template and small change to transform_data err messages.
> moving README to extensions

- resources/sdk/clisdkclient/extensions/go.mod
- resources/sdk/clisdkclient/extensions/go.sum
Added go packages to clisdkclient
> clisdkclient build fix for SDK invocations

- resources/sdk/clisdkclient/extensions/go.mod
- resources/sdk/clisdkclient/extensions/go.sum
missing dependencies were causing a build failure in the cli
> adding missing dependencies for the cli

- resources/sdk/purecloudjavascript-guest/templates/package.mustache
- resources/sdk/purecloudjavascript/templates/package.mustache
Reverts purecloudlabs/platform-client-sdk-common#377
> Revert "rolling back superagent version"

- npm-shrinkwrap.json
- resources/sdk/webmessagingjava/templates/WebMessagingClient.mustache
session object is not returning an id anymore
> session object is not returning an id anymore

- README.md
- resources/sdk/webmessagingjava/templates/WebMessagingClient.mustache
allow to publish currently event that are currently in beta : end user clear conversation. Similar to disconnect but for end user, not agent side
> improve webmessaging sdk to publish conversation clear events

- resources/sdk/clisdkclient/extensions/services/commandservice.go
The `routing skillgroups list` endpoint returns a `NextUri` containing a query param `after`; the cursor that points to the next item. So the style is `NextUri` with cursor pagination logic. The bug came about because, with this style, the query param was assumed to always be called `cursor`, but this endpoint uses `after`.
> Devengage-1987: Fixing bug in pagination logic

- resources/sdk/purecloudjava/templates/ApiClient.mustache
- resources/sdk/purecloudjava/templates/README.mustache
- resources/sdk/purecloudjava/templates/operation_example.mustache
> [DEVTOOLING-265] Add PCKE Support to Java Platform SDK

- resources/sdk/purecloudgo/templates/README.mustache
- resources/sdk/purecloudgo/templates/configuration.mustache
- resources/sdk/purecloudgo/templates/operation_example.mustache
> [DEVTOOLING-266] Add PCKE Support to Go Platform SDK

- resources/sdk/purecloudjavascript/templates/ApiClient.mustache
- resources/sdk/purecloudjavascript/templates/README.mustache
- resources/sdk/purecloudjavascript/templates/api_doc.mustache
- resources/sdk/purecloudjavascript/templates/index.d.ts.mustache
- resources/sdk/purecloudjavascript/templates/operation_example.mustache
> [DEVTOOLING-267] Add PCKE Support to Javascript Platform SDK

- resources/sdk/purecloudpython/templates/README.mustache
- resources/sdk/purecloudpython/templates/api_client.mustache
- resources/sdk/purecloudpython/templates/operation_example.mustache
> [DEVTOOLING-264] Add PCKE Support to Python Platform SDK

- resources/sdk/pureclouddotnet/extensions/Extensions/AuthExtensions.cs
- resources/sdk/pureclouddotnet/templates/README.mustache
> [DEVTOOLING-254] Add PCKE Support to .Net Platform SDK

- resources/sdk/purecloudgo/templates/operation_example.mustache
Update in Go SDK Operation Example Documentation
> [DEVTOOLING-322] Problems with the GO SDK documentation in API explorer

- resources/sdk/clisdkclient/extensions/cmd/profiles/createprofile.go
- resources/sdk/clisdkclient/extensions/config/config.go
- resources/sdk/clisdkclient/extensions/mocks/mockclientconfig.go
- resources/sdk/clisdkclient/extensions/models/oauthWebpage.go
- resources/sdk/clisdkclient/extensions/restclient/restclient_test.go
- resources/sdk/clisdkclient/extensions/services/commandservice_test.go
- resources/sdk/clisdkclient/extensions/utils/general.go
- resources/sdk/clisdkclient/templates/README.md
- resources/sdk/clisdkclient/templates/restclient.mustache
Add OAuth PKCE Support in GC CLI SDK
> [DEVTOOLING-252] Add OAuth PKCE Support in GC CLI SDK

- resources/sdk/purecloudjavascript/templates/ApiClient.mustache
- resources/sdk/purecloudjavascript/templates/README.mustache
- resources/sdk/purecloudjavascript/templates/configuration.mustache
- resources/sdk/purecloudjavascript/templates/index.d.ts.mustache
Gateway/Path Configuration for Javascript SDK
> [DEVTOOLING-670] Update path proxy config to Javascript SDK

- resources/sdk/clisdkclient/resources/operationNameOverrides.json
Internal CLI SDK - resolving operation path/command name conflict
> Internal CLI SDK - resolving operation path/command name conflict

- resources/sdk/purecloudpython/extensions/gateway_configuration.py
- resources/sdk/purecloudpython/templates/README.mustache
- resources/sdk/purecloudpython/templates/__init__package.mustache
- resources/sdk/purecloudpython/templates/api_client.mustache
- resources/sdk/purecloudpython/templates/configuration.mustache
Add path proxy config to Python SDK
> [DEVTOOLING-667] Add path proxy config to Python SDK

- resources/sdk/pureclouddotnet/extensions/Extensions/AuthExtensions.cs
- resources/sdk/pureclouddotnet/templates/ApiClient.mustache
- resources/sdk/pureclouddotnet/templates/Configuration.mustache
- resources/sdk/pureclouddotnet/templates/README.mustache
Add Path proxy config .NET SDK
> [DEVTOOLING-666] Add Path proxy config .NET SDK

- resources/sdk/clisdkclient/resources/operationNameOverrides.json
CLI SDK Fix - Conflict in operation name
> CLI SDK Fix - Conflict in operation name

- resources/sdk/clisdkclient/resources/operationNameOverrides.json
Fix CLI SDK Operation Name Conflict (Dev/Internal)
> [NO-JIRA] Fix CLI SDK Operation Name Conflict

- resources/sdk/clisdkclient/resources/operationNameOverrides.json
Fixing new conflicts on CLI SDK preventing Internal Build
> [NO-JIRA] Fixing new conflicts on CLI SDK

- modules/builder/builder.ts
Modification of the builder script to quarantine some internal endpoints with improper swagger definition (multipart/form-data).
The operationIds to quarantine are defined directly in the builder script.
It could be externalized to the different config.json files (for each language) if it is preferred to do this that way.
> [NO-JIRA] Quarantine endpoints

- resources/sdk/purecloudpython/extensions/utils.py
- resources/sdk/purecloudpython/scripts/compile.sh
- resources/sdk/purecloudpython/scripts/publishPyPi-external.sh
- resources/sdk/purecloudpython/scripts/publishPyPi-internal.sh
- resources/sdk/purecloudpython/scripts/publishPyPi.sh
- resources/sdk/purecloudpython/templates/api.mustache
- resources/sdk/purecloudpython/templates/api_client.mustache
- resources/sdk/purecloudpython/templates/configuration.mustache
- resources/sdk/purecloudpython/templates/model.mustache
- resources/sdk/purecloudpython/templates/requirements.txt
- resources/sdk/purecloudpython/templates/rest.mustache
- resources/sdk/purecloudpython/templates/setup.mustache
- resources/sdk/purecloudpython/templates/test-requirements.mustache
- resources/sdk/purecloudpython/templates/tox.mustache
Python Update Phase 1
Update python minimum version to 3.9
Update dependencies
Remove six direct dependencies
> [DEVTOOLING-1084] Python Update Phase 1

- resources/sdk/webmessagingjava/scripts/combine-swagger.ts
Fix WebMessaging SDK download file error
> [NO-JIRA] Fix WebMessaging SDK download file error

- resources/sdk/purecloudjava/templates/ApiClient.mustache
- resources/sdk/purecloudjava/templates/README.mustache
- resources/sdk/purecloudjava/templates/model.mustache
- resources/sdk/purecloudjava/templates/pojo.mustache
Generate default null for List class field in SDK
> [DEVTOOLING-1100] Java empty list

- modules/builder/builder.ts
Remove operationIds from quarantine and introduce futur aliases
> [NO-JIRA] OperationId Conflict and Alias

- resources/sdk/purecloudpython/extensions/utils.py
- resources/sdk/purecloudpython/scripts/compile.sh
- resources/sdk/purecloudpython/scripts/publishPyPi-external.sh
- resources/sdk/purecloudpython/scripts/publishPyPi-internal.sh
- resources/sdk/purecloudpython/scripts/publishPyPi.sh
- resources/sdk/purecloudpython/scripts/setup.cfg
- resources/sdk/purecloudpython/templates/api.mustache
- resources/sdk/purecloudpython/templates/api_client.mustache
- resources/sdk/purecloudpython/templates/configuration.mustache
- resources/sdk/purecloudpython/templates/model.mustache
- resources/sdk/purecloudpython/templates/requirements.txt
- resources/sdk/purecloudpython/templates/rest.mustache
- resources/sdk/purecloudpython/templates/setup.mustache
- resources/sdk/purecloudpython/templates/test-requirements.mustache
- resources/sdk/purecloudpython/templates/tox.mustache
Update Platform API Python SDK runtime and dependencies
> [DEVTOOLING-1084] Python SDK - Update to 3.9

- resources/sdk/purecloudjava/templates/pom.xml
Update Java SDK Dependencies and Plugins (dependabot alerts)
> [DEVTOOLING-1176] Update Java SDK Dependencies

- resources/sdk/webmessagingjava/templates/README.mustache
Update link to Genesys forums/communities
> Update link to Genesys forums/communities

- resources/sdk/pureclouddotnet/templates/README.mustache
- resources/sdk/purecloudjava/templates/README.mustache
- resources/sdk/purecloudpython/templates/README.mustache
Handle Unknown Enum Values Gracefully in SDKs
> [DEVTOOLING-1164] Document OutdatedSdkVersion enumeration value

- resources/sdk/purecloudjava/templates/pom.xml
Another Java SDK dependencies update to resolve latest dependabot alerts
> [NO-JIRA] Resolve Dependabot Java SDK alerts

- resources/sdk/webmessagingjava/templates/WebMessagingClient.mustache
the code for propagating the tracingId in the responses is not working, doing it another way
> fix problem with tracingId

- resources/sdk/purecloudjava/extensions/connector/okhttp/OkHttpResponse.java
Fix Java SDK OkHttp response unclosed bodies
> [DEVTOOLING-1219] Fix OkHttp response unclosed bodies

- resources/sdk/clisdkclient/resources/operationNameOverrides.json
Resolve latest operation name conflicts for CLI dev build
> [NO-JIRA] Resolve latest operation name conflicts for CLI dev build

- resources/sdk/purecloudgo/templates/README.mustache
- resources/sdk/purecloudgo/templates/apiclient.mustache
Fix Go SDK Gateway Configuration: computation of url and documentation
> [NO-JIRA] Fix Go SDK Gateway Configuration

- resources/sdk/purecloudgo/extensions/default_httpclient.go
- resources/sdk/purecloudgo/extensions/usersapiproxy_test.go
- resources/sdk/purecloudgo/templates/README.mustache
Fix Go SDK PreHook test and documentation
Empty Printf interface
> [NO-JIRA] Fix Go SDK PreHook

- resources/sdk/purecloudjavascript/templates/api.mustache
JS SDK - Check string path param for empty string
> [DEVTOOLING-1259] JS SDK - Check string path param for empty string

- package.json
- resources/scripts/pm2.config.cjs
Update Jenkins runtime to NodeJS 20.x
> [DEVTOOLING-1231] Update Jenkins runtime to NodeJS 20.x

- resources/sdk/purecloudjava-guest/templates/pom.xml
- resources/sdk/purecloudjava/templates/pom.xml
Update Java SDK netty version (CVE)
> [DEVTOOLING-1338] Update Java SDK netty version (CVE)

- resources/sdk/purecloudjava/templates/ApiClient.mustache
- resources/sdk/purecloudjava/templates/pom.xml
Adding necessary jsr310 dependency for java.time.Duration parsing
> [DEVTOOLING-1367] Adding necessary jsr310 dependency for java.time.Duration parsing
