purecloudlabs/platform-client-sdk-common

resources/sdk/purecloudjava/templates/ApiClient.mustache, resources/sdk/purecloudjava/templates/api.mustache, resources/sdk/purecloudjava/templates/apiException.mustache, resources/sdk/purecloudjava/templates/api_async.mustache, resources/sdk/purecloudjava/templates/requestBuilder.mustache
Cleaned up the implementation of `invoke` in `ApiClient` quite a bit and moved the onus of the exception handling into the API classes.
=> API-2464 Refactored ApiClient and moved exception handling to API classes

resources/sdk/purecloudjava/templates/apiException.mustache
API returns this casing:
```
Date: Mon, 08 Jul 2019 16:05:37 GMT
Expires: 0
ININ-Correlation-Id: 6fcf53ef-5402-4c23-921e-d67576d39409
```
Testing with an exception catch and `e.getCorrelationId` and `e.getHeader("ININ-Correlation-Id")` side by side results in a null for the former and the correct value for the latter.
=> Correct casing of correlation id header name.

resources/sdk/purecloudpython/scripts/SdkTests.py, resources/sdk/purecloudpython/templates/README.mustache, resources/sdk/purecloudpython/templates/api_client.mustache
Updated python to include both a client credential helper and saml2bearer helper. The application flow works as such you use the authentication function with creates an api instance and sets the token in that instance. You then pass that api instance into the calling classes to make calls from there
=> Adding clientcredential helperand saml2bearer helper

resources/sdk/pureclouddotnet/extensions/Client/PureCloudRegionHosts.cs, resources/sdk/pureclouddotnet/templates/test-SdkTests.mustache, resources/sdk/purecloudjava-guest/extensions/PureCloudRegionHosts.java, resources/sdk/purecloudjava/extensions/PureCloudRegionHosts.java, resources/sdk/purecloudjava/tests/SdkTests.java, resources/sdk/purecloudjavascript-guest/extensions/PureCloudRegionHosts.js, resources/sdk/purecloudjavascript/extensions/PureCloudRegionHosts.js, resources/sdk/purecloudjavascript/scripts/test/index.js, resources/sdk/purecloudpython/extensions/purecloud_region_hosts.py, resources/sdk/purecloudpython/scripts/SdkTests.py
Adding the following regions to the SDKs:
- us_west_2 - usw2.pure.cloud
- ca_central_1 - cac1.pure.cloud
- ap_northeast_2 - apne2.pure.cloud
- eu-west-2 - euw2.pure.cloud
=> API 5201 - Add new regions to SDKs

resources/sdk/purecloudjava/extensions/connector/apache/ApacheHttpCredentialsProvider.java
Fixes bug where in some cases the "realm" would be a non-default value and AuthScope instances would have a different hashcode.
=> Using a String as the key in HashMap instead of AuthScope object

resources/sdk/pureclouddotnet/extensions/Extensions/Notifications/NotificationHandler.cs
Requested by customer here: https://developer.mypurecloud.com/forum/t/how-to-use-web-socket-through-proxy-using-notificationhandler/3980
=> API-3932 Add websocket proxy support to .net sdk

resources/sdk/purecloudpython/templates/rest.mustache
Issue reported by customer here: https://developer.mypurecloud.com/forum/t/concurrent-api-requests/6858
The "maxsize" keyword argument is needed to increase the number of connections used when pooling connections.
"block" is set to True so no more than "maxsize" connections will be used at a time.
=> API-5046 Fixing python SDK Thread Pool Setting

resources/sdk/pureclouddotnet/scripts/compile.sh, resources/sdk/pureclouddotnet/templates/ApiClient.mustache, resources/sdk/pureclouddotnet/templates/Configuration.mustache, resources/sdk/pureclouddotnet/templates/README.mustache, resources/sdk/pureclouddotnet/templates/TestProject.mustache, resources/sdk/pureclouddotnet/templates/packages_test.config.mustache, resources/sdk/pureclouddotnet/templates/test-ApiClientTests.mustache, resources/sdk/pureclouddotnet/templates/test-csproj.mustache, resources/sdk/pureclouddotnet/templates/test-packages.mustache
```
Running tests...
NUnit Console Runner 3.8.0 
Copyright (c) 2018 Charlie Poole, Rob Prouse
Runtime Environment
OS Version: MacOSX 18.7.0.0 
CLR Version: 4.0.30319.42000
Test Files
/Users/deerghayu/IdeaProjects/DEER/platform-client-sdk-common/output/pureclouddotnet/build/bin/PureCloudPlatform.Client.V2.Tests.dll
=> PureCloudPlatform.Client.V2.Tests.SdkTests.TraceBasicInformation
PURECLOUD_ENVIRONMENT=mypurecloud.com
PURECLOUD_CLIENT_ID=7de3af06-c0b3-4f9b-af45-72f4a14037cc
userEmail=69a4f576-c084-4428-9817-3519092b928b@mypurecloud.com
=> PureCloudPlatform.Client.V2.Tests.SdkTests.CreateUser
Created user with ID f23c3595-b1ff-47cd-be06-3bcccf54358f
Run Settings
DisposeRunners: True
WorkDirectory: /Users/deerghayu/IdeaProjects/DEER/platform-client-sdk-common/output/pureclouddotnet/build …
```
=> API-5107 Add retry logic to the .NET SDK

resources/sdk/purecloudjavascript/templates/ApiClient.mustache
The JS SDK was using "encodeURI" for the redirect URI, this was causing redirect URIs with more than one parameter to be malformed.
Solution was to change "encodeURI" to "encodeURIComponent"
=> API-5248 JS SDK not encoding redirect uri correctly

resources/sdk/purecloudpython/templates/api_client.mustache
The `result` field is typed with `ArrayNode` but it's response is generic and can not be strictly typed. So we use the result from `json.loads` directly instead of deserializing it with `ArrayNode` definition.
=> Use generic object for `results` field in `api/v2/search`

resources/sdk/purecloudjavascript/templates/package.mustache
The 'module' field is a newer alternative to 'jsnext:main', and helps allow the package to be consumed as raw ES Modules.  
We ran into this issue when trying to consume this package through Snowpack, which is a non-bundling build tool for JS development, and prefers to consume dependencies as ES Modules, rather than in AMD or CJS formats.
=> Add 'module' field to package.json

README.md
Fixes the README links to point to the current wiki, and adds a slightly more specific link under "Generating the SDK locally".
=> Fix links to the wiki in the README

resources/sdk/purecloudjavascript-guest/templates/rollup-cjs-for-browserify.config.mustache, resources/sdk/purecloudjavascript/templates/rollup-cjs-for-browserify.config.mustache
We had some downstream pain consuming this library in a bundled web app, due to this code:
```js
if (typeof window === 'undefined' &&
typeof require === 'function' &&
require('fs') &&
param instanceof require('fs').ReadStream) {
return true;
}
```
Although the `require('fs')` doesn't actually get run, webpack was convinced that 'fs' was a dependency when trying to build, due to the require('fs') import.
We're actually using webpack indirectly through snowpack, (I have no little doubt our non-conventional setup is part of the issue), and we can work around this on our end, but it's nice if the web bundle just doesn't contain that code at all, so this uses a rollup replacement to remove it.
I confirmed that with this addition to the rollup config, the entire block listed above is removed …
=> Use rollup replace plugin to remove some node logic from the web bundle

resources/sdk/clisdkclient/extensions/cmd/externalcontacts/externalcontacts.go, resources/sdk/clisdkclient/resources/resourceDefinitions.json
Add basic support for External Contacts to the Genesys Cloud CLI.
This PR add support single-entity CRUD, scan, and search operations for Contacts and External Organizations.
Notes and relationships will be added later due to some complication.
@ronanwatkins @carnellj @timsmithgenesys
=> Add basic externalcontacts support to Genesys Cloud CLI

resources/sdk/purecloudgo/templates/apiresponse.mustache
When the public API returns a 400 with an error response body, the Go SDK is throwing this error: `json: cannot unmarshal string into Go struct field APIError.messageWithParams of type map[string]interface {}`
This is because the `messageWithParams` attribute is actually a string. The `messageParams` attribute is what contains the map.
=> Fix Go SDK error body serialization

resources/sdk/purecloudgo/templates/api.mustache, resources/sdk/purecloudgo/templates/apiclient.mustache
Prevent always tracing default headers as this spams logs when one is added. If needed, they will be traced on line 133 along with the full Request when the debug setting is enabled.
=> Remove default header trace in Go SDK

resources/sdk/purecloudgo/templates/apiclient.mustache
Using the SetBody method is required to ensure the the retryablerequest library is able to rewind the body for retries. Otherwise it sends an empty body in the first retry. https://github.com/hashicorp/go-retryablehttp/blob/v0.7.0/client.go#L126
=> Use SetBody on retryablerequest to ensure body can be resent

resources/sdk/purecloudgo/templates/apiresponse.mustache
The Go SDK is returning JSON serialization errors when details are included in an error response.
=> Serialize error response details as an array of objects

resources/sdk/clisdkclient/extensions/cmd/profiles/createprofile.go, resources/sdk/clisdkclient/extensions/config/config.go, resources/sdk/clisdkclient/extensions/mocks/mockclientconfig.go, resources/sdk/clisdkclient/extensions/services/commandservice.go, resources/sdk/clisdkclient/extensions/services/commandservice_test.go, resources/sdk/clisdkclient/templates/README.md, resources/sdk/clisdkclient/templates/restclient.mustache, resources/sdk/clisdkclient/templates/root.mustache
1. Create profile flow updated to allow for either an access token, client credentials or both during create profile. If a user provides an access token, this will be used over client credentials.
2.  An environment variable GENESYS_CLOUD_ACCESS_TOKEN can also be used to set the token. This will take priority over an access token in config.
3. A parameter override --accesstoken can also be used to set the token. This will take priority over a token set as an environment variable or a token in config.
=> allowing user to specify an access token during create profile, or as an environment variable or as a parameter override

resources/sdk/clisdkclient/extensions/utils/render.go
I added `---` to the line preceding a YAML response object. I think this could be more convenient for when a user wants to process multiple YAML response bodies stored in the same file as they would be separated.
=> NO-JIRA - Made a small change to how YAML data is printed.

resources/sdk/clisdkclient/extensions/cmd/groups_members/addmembers.go, resources/sdk/clisdkclient/extensions/retry/retry.go, resources/sdk/clisdkclient/extensions/services/commandservice.go, resources/sdk/clisdkclient/extensions/services/commandservice_test.go, resources/sdk/clisdkclient/extensions/utils/general.go, resources/sdk/clisdkclient/templates/README.md
Allowing users to provide a directory path to the --directory flag or to the -d short flag containing request bodies to "bulk" create or update data. For example, bulk creating or updating user data. If there is one file in the directory, the response will be a single object (similar to how the --file flag would work when provided with a single file for making a request). If there is more than one file (request bodies) in the directory then the response will be and array of objects returned from each individual request. If there are errors with any of the requests, the error objects will be concatenated onto the response where the successful response object would have been otherwise.
=> Slurping in multiple files from a directory for "bulk" creating or updating data.

resources/sdk/clisdkclient/extensions/restclient/tls/generate_cert.go, resources/sdk/clisdkclient/extensions/restclient/tls/generate_cert_test.go
The error `restclient_test.go:101: err should be nil, got: open /tmpcert.pem: permission denied` in the jenkins build seems to have been caused by the value in `os.TempDir()` not including a / character at the end. This change should fix that
=> Added check for '/' suffix in os.TempDir

resources/sdk/purecloudjava/templates/pom.xml
jackson version 2.13.2.1 could not be found in maven central causing a build failure, so rolling back to version 2.13.2
=> rolling back jackson version for java sdk

resources/sdk/purecloudjava/templates/pom.xml
dependabot updated testng from version 7.5 to version 7.6.0 recently. Looks like the new testng version requires jdk 11 but we are using jdk 8. so rolling back testng to most recent version where it works.
=> fixing java sdk build failure

resources/sdk/purecloudjavascript/templates/ApiClient.mustache, resources/sdk/purecloudjavascript/templates/package.mustache
Added qs dependency to correctly stringify url encoded parameters for javascript sdk.
See: https://axios-http.com/docs/urlencoded
=> fix: add qs to correctly stringify url encoded parameters

.github/dependabot.yml
according to [Specifying dependencies and versions to ignore](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore:~:text=For%20Java%20dependencies%2C%20the%20format%20of%20the%20dependency%2Dname%20attribute%20is%3A%20groupId%3AartifactId%20(for%20example%3A%20org.kohsuke%3Agithub%2Dapi))
=> fixing dependabot ignore dependency name

resources/sdk/webmessagingjava/templates/api_json.mustache
The other symlinks have already been reverted and this is causing internal build failures.
The other reverts are here - https://github.com/purecloudlabs/platform-client-sdk-common/commit/42e2183b90179b50bf49b8c04210f1875da6789d
=> Removing symlink for webmessagingsdk api_json template

resources/sdk/pureclouddotnet-guest/extensions/Client/UpgradeSdkEnumConverter.cs, resources/sdk/pureclouddotnet/config.json, resources/sdk/pureclouddotnet/extensions-test/UpgradeSdkEnumConverterTests.cs, resources/sdk/pureclouddotnet/extensions/Client/UpgradeSdkEnumConverter.cs, resources/sdk/pureclouddotnet/templates/AssemblyInfo.mustache, resources/sdk/pureclouddotnet/templates/test-csproj.mustache
I was profiling an application that uses the Platform Client SDK (but also does many other things,) and I noticed that 25% of objects allocated on the .NET managed heap were coming from `UpgradeSdkEnumConverter`.  It uses reflection to map strings to enum values.
The implementation proposed on this PR caches the mapping of strings to enum values on the first run for each enum type, and then subsequent runs don't allocate any objects on the managed heap.  I didn't intend to make any changes to the functionality, so I added some new unit tests that pass with both the old and proposed implementations.
I wrote some benchmarks with BenchmarkDotNet to quantify the performance impact of the proposed change:
* `ReadJson` - just calls `UpgradeSdkEnumConverter.ReadJson()` (the method I optimized)
* …
=> Refactor UpgradeSdkEnumConverter to cache the result instead of using reflection each time it reads or writes JSON

resources/sdk/purecloudgo/extensions/platformclientv2_test.go, resources/sdk/purecloudgo/templates/README.mustache, resources/sdk/purecloudgo/templates/apiclient.mustache, resources/sdk/purecloudgo/templates/model.mustache
Adds a helper function to models in the Go SDK to manually control which properties are serialized, regardless of their value (including nil). Example:
```go
patchBody := platformclientv2.Patchactionmap{}
patchBody.SetField("Id", platformclientv2.String("777-777"))
patchBody.SetField("Version", platformclientv2.Int(7))
patchBody.SetField("DisplayName", nil)
patchAction := platformclientv2.Patchaction{}
patchAction.SetField("ActionTargetId", platformclientv2.String("12345"))
patchBody.SetField("Action", &patchAction)
```
yields:
```json
{
"action": {
"actionTargetId": "12345"
},
"displayName": null,
"id": "777-777",
"version": 7
}
```
This allows applications to explicitly construct request objects that will be serialized exactly the way they are created, ignoring the default serialization …
=> DEVENGAGE-1323 field serialization opt in

resources/sdk/webmessagingjava/templates/WebMessagingClient.mustache
add startNew param for configure session after disconnect event for webmessaging SDK. This param is to be used after a Presence event of type disconnect is received, when feature disconnect is enabled and configure to set sessions to read-only after such event
Also adding methods to check if message contains events
=> webmessaging - add startNew param for configure session after disconnect event

resources/sdk/pureclouddotnet/extensions-test/UpgradeSdkEnumConverterTests.cs, resources/sdk/pureclouddotnet/extensions/Client/UpgradeSdkEnumConverter.cs
I recently noticed that my change on PR #499 caused an unintentional change in behavior in cases where it writes `OUTDATED_SDK_VERSION` as a value to JSON.   Before that PR, it would write `"OUTDATED_SDK_VERSION"`, but after that PR it would write nothing.   This PR keeps the optimization from PR #499 but restores the original behavior in this case.
This is a fringe use case -- it should be unusual to serialize the actual value `OUTDATED_SDK_VERSION`, but that PR was not intended to change any behavior.  It caused a problem in a very specific use case in my application.
=> Fix unintentional change in behavior of UpgradeSdkEnumConverter serializing OUTDATED_SDK_VERSION

modules/builder.js
This PR is related to https://bitbucket.org/inindca/platform-client-sdk-internal-config/pull-requests/91. Here we check if the build is an internal SDK build and that the command line argument `build-contains-upstream-changes` is present. If those conditions are met, we check if the `swaggerDiff.changeCount == 0` and if it is, throw an error failing the build.
=> jenkins swagger check

README.md, resources/sdk/webmessagingjava/templates/FileUtils.mustache, resources/sdk/webmessagingjava/templates/WebMessagingClient.mustache
web messaging is now using the "support content profile" to allow or refuse file attachment. 
Adding a new endpoint to query the current configuration (retrieve the allowed media types)
=> enable Support content profile feature for web messaging

resources/sdk/webmessagingjava/templates/WebMessagingClient.mustache
Adding a way to have like an user-agent signature when connecting to the websocket for webmessaging.
Default connecting method will not fill this and the default will be used ("WebMessagingSDK-{{version of the sdk}}")
=> Shyrka 2103 include application details at connection

resources/sdk/pureclouddotnet/extensions/Extensions/Notifications/NotificationHandler.cs
Hey there! This pull request addresses an important requirement for situations where users need to have more than one NotificationHandler instance running concurrently in their application, such as having a separate thread per organization.  Without these modifications, a default NotificationsApi is created, which internally initializes a static Configurations object in its constructor.
To overcome this limitation, this pull request introduces additional constructors to the NotificationHandler class. These constructors allow users to pass their own NotificationsApi instance, ensuring that each NotificationHandler operates independently with its own dedicated NotificationsApi object. This modification helps prevent potential conflicts and ensures thread-safety when multiple …
=> Add ctors for NotificationHandler with NotificationsApi parameter

resources/sdk/purecloudjavascript-guest/templates/README.mustache, resources/sdk/purecloudjavascript-guest/templates/configuration.mustache, resources/sdk/purecloudjavascript-guest/templates/index.d.ts.mustache, resources/sdk/purecloudjavascript/templates/README.mustache, resources/sdk/purecloudjavascript/templates/configuration.mustache, resources/sdk/purecloudjavascript/templates/index.d.ts.mustache
Reported in https://developer.genesys.cloud/forum/t/cant-use-purecloud-platform-client-v2-with-node-js-typescript/12151/10
> ReferenceError: You are trying to import a file after the Jest environment has been torn down
This warning reveals itself when live reloading is enabled and the context of the runtime is Node.js (not a browser). Recommended resolutions did not appear to have an effect on resolving the warning. The warning leads to having an impact on the success of Jest executions in CI/CD tooling.
In this commit:
- Update configuration.js to use ES6 imports. Removes runtime ESM require() from functions. Including the TS config for allowSyntheticDefaultImports in a consuming application does not appear to resolve the warning.
- Update Add TS definition for …
=> Update Configuration imports to ES6

resources/sdk/pureclouddotnet/templates/ApiClient.mustache
It is currently available in CallApi (sync) but not in CallApiAsync
=> Add logging to CallApiAsync in .NET SDK

resources/sdk/pureclouddotnet/extensions/Extensions/AuthExtensions.cs, resources/sdk/pureclouddotnet/templates/ApiClient.mustache, resources/sdk/pureclouddotnet/templates/README.mustache, resources/sdk/pureclouddotnet/templates/api.mustache
Fix for .Net SDK for HTTP Responses with duplicate header names.
=> [DEVTOOLING-767] Net SDK Fix for duplicate header names in HTTP Responses

resources/sdk/clisdkclient/extensions/utils/general.go
CLI SDK Client Fix - Manage unset Int and Float command parameters
If a command parameter, of type int or float, with no default value, is not set when calling the CLI command (i.e. not specified in the CLI command and its parameters), it will be incorrectly interpreted as 0.
-> "strconv.Atoi" of an empty string = 0
As Int and Float flags are converted back to a string, the proposal is to manage int and float command parameters as strings (similar to how bool and time.Time are currently handled in the CLI SDK).
=> CLI SDK Client Fix - Manage unset Int and Float command parameters

resources/sdk/purecloudjavascript/templates/index.d.ts.mustache
The API class constructors optionally take an ApiClient instance. This PR adds a construtor to the TypeScript definitions to reflect this.
=> Add API class constructor to TypeScript definitions

resources/sdk/purecloudjava-guest/templates/ApiClient.mustache, resources/sdk/purecloudjava-guest/templates/Logger.mustache, resources/sdk/purecloudjava/templates/ApiClient.mustache, resources/sdk/purecloudjava/templates/Logger.mustache, resources/sdk/webmessagingjava/templates/ApiClient.mustache
Temporary rollback on Java Object Mapper settings (meant for empty arrays), as it has a side effect on a couple of API endpoints (on empty string and empty object). Change will be evaluated again to take into account this.
=> [NO-JIRA] Temporary rollback on Java Object Mapper

resources/sdk/purecloudjavascript/templates/ApiClient.mustache, resources/sdk/purecloudjavascript/templates/README.mustache, resources/sdk/purecloudjavascript/templates/index.mustache
https module is only supported with nodejs.
Import at the beginning of the file is replaced with require('https') in the code. setting of MTLS certificates is only supported with nodejs application - browser client is to manage and to support MTLS aspect in case of webapps.
=> [DEVTOOLING-1006] Javascript Warning in Vite for https library

modules/builder/builder.ts, resources/sdk/purecloudjava/config.json
Java SDK - Force API endpoints, per Tag (SCIM), to use csv collectionFormat instead of multi
Query Parameters of type array will be sent via single attribute with comma separated values
=> [NO-JIRA] Java SDK - Force API endpoints, per Tag (SCIM), to use csv collectionFormat

resources/sdk/clisdkclient/resources/operationNameOverrides.json
New endpoints causing some name conflicts in CLISDK Client
=> [NO-JIRA] Operation Name Conflicts in CLISDK Client

resources/sdk/pureclouddotnet/templates/Configuration.mustache, resources/sdk/pureclouddotnet/templates/README.mustache
Configuration constructor currently leverages the ApiClient of the Default Configuration instance (static). The change is to facilitate the creation of Configuration and ApiClient instances that dot not rely on the Default Configuration singleton - allowing to maintain distinct ApiClients to different regions (or same region with different access tokens).
=> [NO-JIRA] .NetSDK - Create distinct Configuration/Configuration.ApiClient instances

modules/builder/builder.ts, modules/swagger/swaggerDiff.ts, resources/sdk/webmessagingjava/scripts/combine-swagger.ts
WebMessaging Swagger v2 specification was missing some information on contracts.
Moved to OpenAPI v3 to get access to these contract information.
The v2 specification then needs a convert/downgrade to version 2 for proper SDK generator processing.
=> [NO-JIRA] WebMessaging Java SDK - fix swagger

modules/builder/builder.ts
On Notification Event Model objects all Integer values should be converted from int to long
=> [DEVTOOLING-1163] Topics integer properties to int64

resources/sdk/clisdkclient/extensions/config/config.go, resources/sdk/clisdkclient/templates/restclient.mustache
Fix CLI Gateway Configuration on empty path params (incorrect uri when the login or api path param is an empty string).
Allow connection to locahost:$port (localhost only allowed at this time).
=> [DEVTOOLING-1186] CLI SDK - Fix Gateway Configuration with empty login or api path params

resources/sdk/purecloudgo/templates/apiclient.mustache
Fix Go SDK Gateway Configuration on empty path params (incorrect uri when the login or api path param is an empty string).
=> [DEVTOOLING-1187] Go SDK - Fix Gateway Configuration with empty login or api path params

resources/sdk/webmessagingjava/templates/WebMessagingClient.mustache, resources/sdk/webmessagingjava/templates/pom.xml.mustache
Update WebMessaging SDK
customer reported missing access to recently added field _tracingId_ in requests. Some methods were missing the ability to set this parameter
- add the parameter to non generated method
- add getter to the underlying websocket, so that in case of missing feature customers still can craft themselves requests
- Added server-side validation as a safety net
changed the way the application name parameter is generating it's default value. It should include the SDK version number if not set by client
Added also parameter _startNew_ for method _configureAuthenticatedSession_ . This parameter was already available to configureSession for un-authenticated user
=> SHYRKA-2902 Update WebMessaging SDK

resources/sdk/purecloudjavascript/templates/ApiClient.mustache
Reported on the community forum: https://community.genesys.com/discussion/possible-bug-in-javascript-sdk-code-documentation#bm731a4dba-5e1b-4b26-a614-01966440ed5b
=> [NO-JIRA] Fix Timeout value in Javascript SDK doc annotation

resources/sdk/clisdkclient/resources/operationNameOverrides.json
Resolving CLI SDK name conflicts on internal/dev pipeline
=> [NO-JIRA] Resolving CLI SDK name conflicts

resources/sdk/purecloudjavascript/templates/ApiClient.mustache, resources/sdk/purecloudjavascript/templates/README.mustache, resources/sdk/purecloudjavascript/templates/index.d.ts.mustache
Fix Javascript SDK boolean and number query parameters
=> [DEVTOOLING-1244] WAIT BEFORE MERGE - Fix Javascript SDK boolean and number query parameters
